AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      FunctionName: EmlCreateChannel
      Handler: com.amazonaws.examples.App::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/eml-create-channel.jar
      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # eg:
      Policies:
        - Statement:
            - Sid: AllowIamRoleCreationPolicy
              Effect: Allow
              Action:
                - iam:GetRole
                - iam:CreateRole
                - iam:AttachRolePolicy
                - iam:PutRolePolicy
                - iam:PassRole
              Resource: '*'
            - Sid: AllowMedialiveChannelCreationPolicy
              Effect: Allow
              Action:
                - medialive:CreateChannel
                - medialive:CreateInput
                - medialive:CreateInputSecurityGroup
              Resource: '*'